#!/bin/sh
#
#*****************************************************************************
#
# Copyright (C) 2019 - 2021 Xilinx, Inc. All rights reserved.
# Copyright (c) 2022 - 2025 Advanced Micro Devices, Inc.  ALL rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#******************************************************************************
#
# Script to start / stop watchdog heartbeats

DAEMON=/usr/bin/watchdog-daemon
start ()
{
	 echo " Starting watchdog-daemon-init"
	 start-stop-daemon -S -o --background -x $DAEMON
}
stop ()
{
	 echo " Stoping watchdog-daemon-init"
	 start-stop-daemon -K -x $DAEMON
}
restart()
{
	 stop
	 start
}
[ -e $DAEMON ] || exit 1
 	case "$1" in
 		start)
 			start; ;;
  		stop)
 			stop; ;;
 		restart)
 			restart; ;;
 		*)
 			echo "Usage: $0 {start|stop|restart}"
 			exit 1
 	esac
exit $?


